### PR TITLE
Add skip assertion if use objects or interfaces

### LINKED ISSUE #174: Generate safety assertions
All* non-method functions functions need to have safety assertions introduced in https://github.com/gtk-rs/gtk/pull/189, e.g.

```rust
impl Box {
    pub fn new(orientation: Orientation, spacing: i32) -> Box {
        assert_initialized_main_thread!();
        ...
```

\* if we take an object that has an assertion in its constructor, it can be skipped, but this optimization is not strictly necessary:
```rust
 impl Layout {
    pub fn new(hadjustment: &Adjustment, vadjustment: &Adjustment) -> Layout {
        skip_assert_initialized!();
        ...
```

The whole feature should probably be optional.

### PR DESCRIPTION
**Pull request by EPashkin**
Closes #174
Cover both `Option<Widget>` and `&[]` (GLib.List) exclusions cases.

### CODE REVIEW

**Comment by gkoz** [comment]
Another thing I forgot is only objects from the current library are eligible, e.g. `PixbufAnimation` constructors don't have the assertions: 
```patch
     pub fn new_from_animation<T: Upcast<gdk_pixbuf::PixbufAnimation>>(animation: &T) -> Image {
-        assert_initialized_main_thread!();
+        skip_assert_initialized!();
         unsafe {
```

**Comment by EPashkin** [comment]
You right.
With limiting by types from current crate checks in `gtk_image_new_from_animation`, `gtk_status_icon_new_from_pixbuf`, `gtk_style_context_reset_widgets` will be not skipped.

**Comment by gkoz** [comment]
Looks good!

**Comment by gkoz** [comment]
@homu r+

**Pull request merged**
