### PR TITLE
parser: read the functions' `throws` attribute, insert GError parameter

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by gkoz** [comment]
@EPashkin you might not like doing this in the parser, I'm open to alternatives. This seems like the only place that can easily see every function. Doing the same in the analysis modules will be more complicated.

**Comment by EPashkin** [comment]
No problem with this, it really parameter.
But may be better add as `ParameterDirection::Error` ?

**Comment by gkoz** [comment]
Would replacing `instance_parameter` with `kind: enum ParameterKind { Normal, Instance, Error }` work?

**Comment by EPashkin** [comment]
Maybe. Not sure what we needed function generation.
So now merge as is, when we needed code with errors, then change.

**Comment by EPashkin** [comment]
No effect on current generated widgets.

**Comment by gkoz** [comment]
@homu r+

**Pull request merged**
