### PR TITLE
Partially implement container handling

### PR DESCRIPTION
**Pull request by gkoz**
`GList` return value is translated to `Vec` correctly now.
Somewhat generalized passing input parameters by reference.

```patch
-    //fn get_children(&self) -> /*Unknown kind*/Unknown rust type: "List TypeId { ns_id: 1, id: 3 }";
-    //fn get_focus_chain(&self, focusable_widgets: /*Unknown kind*/Unknown rust type: "List TypeId { ns_id: 1, id: 3 }") -> bool;
+    fn get_children(&self) -> Vec<Widget>;
+    //fn get_focus_chain(&self, focusable_widgets: /*Unimplemented*/Vec<Widget>) -> bool;

-    //fn set_focus_chain(&self, focusable_widgets: /*Unknown kind*/Unknown rust type: "List TypeId { ns_id: 1, id: 3 }");
+    //fn set_focus_chain(&self, focusable_widgets: /*Unimplemented*/&[Widget]);

-    //fn set_icon(&self, icon: Option<gdk_pixbuf::Pixbuf>);
-    //fn set_icon_from_file(&self, filename: Fundamental: Filename, error: Option</*Unknown kind*/Unknown rust type: "Error">) -> bool;
-    //fn set_icon_list(&self, list: /*Unknown kind*/Unknown rust type: "List TypeId { ns_id: 7, id: 2 }");
+    //fn set_icon(&self, icon: Option<&gdk_pixbuf::Pixbuf>);
+    //fn set_icon_from_file(&self, filename: Fundamental: Filename, error: /*Unknown kind*/Unknown rust type: "Error") -> bool;
+    //fn set_icon_list(&self, list: /*Unimplemented*/&[gdk_pixbuf::Pixbuf]);
```

### CODE REVIEW

**Comment by EPashkin** [comment]
Don't understand reason for Nullable, but look very good.

**Comment by gkoz** [comment]
Apparently it's not considered a good style to use boolean parameters. A named type adds explicitness and type safety.

**Comment by EPashkin** [comment]
Then not better make Nullable enum{NotNullable, CanBeNull} ? (can't find good names)

**Comment by gkoz** [comment]
It seems the good names might be `Nullable { Yes, No }` and this isn't much different from `Nullable(pub bool)`.

**Comment by EPashkin** [comment]
Yes :(
And long names useful only with `use library::Nullable::NotNullable` that make more difficult change used value (from NotNullable to CanBeNull).
But use `Nullable(false)` don't seems right for me.

**Comment by gkoz** [comment]
I'll probably have to make it an enum then. Do you happen to have some Rust examples where such yes/no enums were used effectively?

**Comment by gkoz** [comment]
A hazard of the enum approach is that `if nullable == Nullable::Nullable` could break if someone added another variant later. Avoiding ifs would not be reliable as well.

**Comment by EPashkin** [comment]
Yes. And safe usage (only one that I found) also don't look good
```
if  !skip_option {
  match nullable {
    Yes => rust_type = rust_type.map_any(|s| format!("Option<{}>", s)),
    No => ()
  }
}
```
So maybe it better just stay plain bool.

**Comment by EPashkin** [comment]
About "it's not considered a good style to use boolean parameters", can you provide some links?
I understand about values that linked with scope (number with unit of measure), but don't hear about just bool.

**Comment by gkoz** [comment]
There's [this bit in Rust style guidelines](http://doc.rust-lang.org/style/features/types/README.html#use-custom-types-to-imbue-meaning;-do-not-abuse-bool,-option-or-other-core-types.-%3Cstrong%3E[fixme:-needs-rfc]%3C/strong%3E)

This kind of advice is all over the internet applying to Java, C++, any language that doesn't support named parameters.

I've seen Rust code with commented annotations like `/* nullable */ false` which seem to just ask for a newtype.

No one has bothered me about [this use of a bool newtype](https://github.com/gtk-rs/gtk/blob/master/src/signal.rs#L57-L59) so far.

**Comment by EPashkin** [comment]
Thanks, I missed this.
Then just don't forget nullable in Parameter.

**Comment by gkoz** [comment]
Switched `Parameter::nullable` to `Nullable`.

**Comment by EPashkin** [comment]
Thanks

**Comment by gkoz** [comment]
@homu r+

**Pull request merged**
