### PR TITLE
Declarations return values

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by EPashkin** [comment]
Can you give me example code for function, returning Records (`gtk_container_get_path_for_child`) ?
Then I add it records this PR.

**Comment by gkoz** [comment]
I don't have a complete plan for the "boxed" types yet. The function would simply call `from_glib_full` on the pointer but we can't assume that any type has a `FromGlibPtr` implementation. Might have to use a whitelist at first.

**Comment by EPashkin** [comment]
Then no Records for now, these functions will be commented
Ready for merge

**Comment by EPashkin** [comment]
Or I can add commit, that changes
```
//fn get_path_for_child(TODO: Params) -> /*Unknown kind*/Unknows rust type: "WidgetPath";
```
to something like
```
//fn get_path_for_child(TODO: Params) -> /*TODO: Record*/WidgetPath;
```

**Comment by gkoz** [comment]
> Or I can add commit, that changes

This might matter if we want to copy-paste some code from the generated files into the manually maintained ones, having to remove these notes would be annoying.

**Comment by EPashkin** [comment]
Fixed type in `Unknows rust type`

**Comment by EPashkin** [comment]
For `this` you refer current line or offered?

**Comment by gkoz** [comment]
I'm fine with both versions right now, it's just if we were to copy these fragments somewhere else the comments might be in the way. But that can be fixed when it actually becomes an issue.

**Comment by EPashkin** [comment]
So I write commit or you just merge?

**Comment by gkoz** [comment]
I'll merge.

**Pull request merged**
