### PR TITLE
Add gtk-sys to tests

### PR DESCRIPTION
**Pull request by EPashkin**
WIP

### CODE REVIEW

**Comment by EPashkin** [comment]
xlib-sys contains only struct and types and bad lines
```
pub type XEvent = c_void;
pub type XEvent = XEvent;
```

**Comment by EPashkin** [comment]
IMHO ready for merge

**Comment by EPashkin** [comment]
`xlib.Window` only used in `GtkPlug` and `GtkSocket`

**Comment by EPashkin** [comment]
Updated info about `gmodule` and `cairo` in https://github.com/gkoz/gir/issues/29

**Comment by EPashkin** [comment]
As all girs.toml contains path to sys, started to think, that its need suffixed with `-sys`

**Comment by gkoz** [comment]
> `pub type XEvent = XEvent;`

I think, we're going to stop cutting of the prefixes anyway.
But we'll need some solution to avoid creating `xlib-sys`, `fontconfig-sys` and so on.

**Comment by gkoz** [comment]
And ideally the `cfg(os = "unix")` stuff could be marked appropriately.

**Comment by EPashkin** [comment]
When we has more info about system dependence we can add statuses that converted to `ignore` on wrong system.

**Comment by EPashkin** [comment]
Was wrong with last.

**Comment by EPashkin** [comment]
We can add status `generate_on_linux` for `GtkPlug` and `GtkSocket` but don't know how to remove `use xlib_sys as xlib_ffi` in correct way.

**Comment by gkoz** [comment]
Thanks.
@homu r+

`gmodule` and what else comes with glib, `gthread`, I think, it makes sense to have them too in case someone wants them.

**Comment by gkoz** [comment]
Oh and I don't mind renaming the gir files.

**Pull request merged**
