### PR TITLE
Generate sys structs

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by EPashkin** [comment]
Don't merge, next is records

**Comment by EPashkin** [comment]
Ok, I fix for.
About Records, normal if I replace `GtkTreeIter{...}` and other two with just `struct`?

**Comment by gkoz** [comment]
Records need to have their fields, most of them are unusable as empty structs.

**Comment by EPashkin** [comment]
Ok, then Records will be manual (or later).
Look to last commit, can I remove GAppLaunchContext and others external?

**Comment by EPashkin** [comment]
About enums: I won't do it in next two days, and as I see, you start some preparation, so maybe you do them.

**Comment by gkoz** [comment]
> Look to last commit, can I remove GAppLaunchContext and others external?

Yeah, they are out of place in the gtk crate.

> About enums: I won't do it in next two days, and as I see, you start some preparation, so maybe you do them.

Okay.

**Comment by EPashkin** [comment]
Ready to merge

**Comment by gkoz** [comment]
Thanks!

**Pull request merged**
