### PR TITLE
Outs as optional return

### LINKED ISSUE #119: Support optional outparam return types
Some functions return `bool` in addition to outparams with the understanding that returning `FALSE` means the outparams haven't been initialized, this should translate to `None`.

Example: `gtk_widget_translate_coordinates`.

### PR DESCRIPTION
**Pull request by EPashkin**
Closes #119

### CODE REVIEW

**Comment by EPashkin** [comment]
Don't found good name for `*_parts` functions

**Comment by gkoz** [comment]
Good job! Might call those "parts" "leaves" if that makes it any clearer. There's a typo in "tuple" in several places.

**Comment by EPashkin** [comment]
Fixed "tuple". Don't change to "leaves" as don't understand its meaning.

**Comment by gkoz** [comment]
Thanks!
@homu r+

**Pull request merged**
