### PR TITLE
Tests gdk and gdk-pixbuf

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by EPashkin** [comment]
`Gdk` uses manual version of `cairo`
Also has problem with GdkEventKey.is_modifier so some `GdkEvent*` commented, may be also for `pub state: [TypeId { ns_id: 1, id: 16 }]`

**Comment by EPashkin** [comment]
Used manual version of `cairo`, as generated contains nothing (may be due no includes in `cairo-1.0.gir`)

**Comment by EPashkin** [comment]
bad field in GdkEvent* now `pub state: [TypeId { ns_id: 1, id: 16 } Gdk.ModifierType]`

**Comment by EPashkin** [comment]
This field contains no `c:type` in gir. Seems this case needed fixed specially.
Can you fix it?

**Comment by EPashkin** [comment]
Possible problem: `GdkPixbuf-2.0.gir` includes `GModule` but we don't need it.

**Comment by EPashkin** [comment]
For `_truncated_record_marker` IMHO better add field name in comments.

**Comment by gkoz** [comment]
Thanks!
@homu r+

**Comment by gkoz** [comment]
Generating `cairo` is problematic, yes. First, we'll need to prepare its GIRs ourselves, it doesn't come with them included. And generating a good GIR is not easy. But then is the issue of it having a number of non-glib dependencies.

I'll look into `GdkEvent` and adding a comment to truncated records.

**Pull request merged**
