### PR TITLE
Generalization of widgets

### PR DESCRIPTION
**Pull request by EPashkin**
Not sure about good name for 'TypeKind::of()',  prefer 'for' but it keyword :(
Also about 'special_type'

### CODE REVIEW

**Comment by EPashkin** [comment]
Forgot update test. Fixed.

**Comment by gkoz** [comment]
I'm not aware of any library other than GTK that pulls those shenanigans with constructors returning a superclass. But is there anything special about `Widget` really? If we see the that a `Foo`'s constructor return `Widget` instead of `Foo` isn't this enough to know it needs to be downcasted?

**Comment by EPashkin** [comment]
Main problem for me was that `IsWidget` (new `IsChildOfSpecialType`) needed library to check if it widget, so `ToTypeKind` needed library also. Also check for widget always call `find_type`.

**Comment by EPashkin** [comment]
And don't forget about "Widget:from_glib_none", that appears in all constructors.

**Comment by gkoz** [comment]
> And don't forget about `Widget:from_glib_none`, that appears in all constructors.

That's what I was thinking of: if the return type `X` doesn't match the constructor's `Y` -- just do `X::from_...().downcast_unchecked()`

**Comment by EPashkin** [comment]
You right. Then maybe TypeKind::Special not needed at all. I try it.

**Comment by EPashkin** [comment]
Tried https://github.com/gkoz/gir/pull/33#issuecomment-118631437 for constructor and it works. Maybe special kind (and all kinds) don't needed. I close this PR after full check.

**Comment by EPashkin** [comment]
Really don't needed. Closing.

**Comment by gkoz** [comment]
Lying about the types isn't limited to constructors, BTW. In `gtk_dialog_get_content_area` they tell us that the type is `Box` but the C type is `GtkWidget*` so supposedly that's what we're meant to put in the ffi definitions. That's going to be fun.
```xml
        <return-value transfer-ownership="none">
          <doc xml:space="preserve">the content area #GtkBox.</doc>
          <type name="Box" c:type="GtkWidget*"/>
        </return-value>
```

**Comment by EPashkin** [comment]
Thanks, added TODO to `TranslateFromGlib`

**Comment by gkoz** [comment]
Unfortunately the same happens in the other direction as well.
In the `gtk_file_chooser_button_new_with_dialog`:
```xml
          <parameter name="dialog" transfer-ownership="none">
            <doc xml:space="preserve">the widget to use as dialog</doc>
            <type name="Dialog" c:type="GtkWidget*"/>
          </parameter>
```

**Comment by EPashkin** [comment]
IMHO with incoming parameters it not problem, only problem with return types

**Pull request closed without merging**
