### PR TITLE
Some comsetic changes

### PR DESCRIPTION
**Pull request by gkoz**
It seems redundant to use the `_ffi` suffix in the sys crates when referring to sibling crates. All of this is FFI already.

### CODE REVIEW

**Comment by EPashkin** [comment]
Will not confusion between sys and normal version without suffix?

**Comment by EPashkin** [comment]
But if all compiled, then no problem.

**Comment by gkoz** [comment]
The normal crates still pick the names they like (sometimes it's just `ffi`) but these crates constitute a self-sufficient layer.

**Comment by gkoz** [comment]
@homu r+

**Pull request merged**
