### PR TITLE
Arrays and bitflags improvements

### PR DESCRIPTION
**Pull request by gkoz**
Add GArray, GByteArray and GPtrArray support.
Make enums and bitflags c_int and c_uint; convert negative bitflags members to positive repr.
Add pango to tests.

### CODE REVIEW

**Comment by gkoz** [comment]
So `G_PARAM_DEPRECATED` is... deprecated and useless. Since we're defining it as a constant, might use the blacklisting facility.

**Comment by EPashkin** [comment]
You sure about this? IMHO it marks parameter as deprecated. But may be really useless for us.

**Comment by gkoz** [comment]
Bah! You're right. I'll continue investigating the enum sizes then

**Comment by EPashkin** [comment]
By way can you change test.sh that it scans *.toml? So we don't need update LIBS

**Comment by EPashkin** [comment]
And about bitfields, IMHO it always unsigned, so better just convert all to u32

**Comment by gkoz** [comment]
> By way can you change test.sh that it scans *.toml? So we don't need update LIBS

Good idea but won't the generator fail because of missing `src` directories? It may need to create them on demand.

**Comment by gkoz** [comment]
Unsigned bitflags seems logical. I guess we'll have to convert rare negative values (`G_LOG_LEVEL_MASK`) to positive representations.

**Comment by gkoz** [comment]
@homu r+

**Comment by EPashkin** [comment]
You create `src` in script, creating also can be added to gir, if you know how to check file existence. I found no stable method.

**Comment by gkoz** [comment]
If the script just globs over the toml files, it won't know which directories to create.

`PathExt::exists` seems unstable but we still have options. For example always create the directory ignoring the `AlreadyExists` error.

**Pull request merged**
