### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by gkoz**
The second commit relies on the recently pushed updates to `glib#object_reform`

### CODE REVIEW

**Comment by EPashkin** [comment]
Look good.

**Comment by gkoz** [comment]
Added another one, fixes some unused and missing 'std::mem` and `std::ptr` imports.

**Comment by EPashkin** [comment]
May be better extract `codegen::function_body_chunk::OutMemMode` to analyze and add method for imports?

**Comment by EPashkin** [comment]
Current code good too.

**Comment by gkoz** [comment]
I'm not very happy with the current patch will consider your suggestion.

**Comment by gkoz** [comment]
While managing imports in analysis seems too early, communicating the needed imports back from chunks seems problematic as well. But it might make sense to move the imports analysis into a separate function.

**Comment by gkoz** [comment]
The imports code is more isolated now and currently I doubt it can be moved to codegen.

**Comment by gkoz** [comment]
@homu r+

**Pull request merged**
