### PR TITLE
Limit out_as_return to unconverted types

### PR DESCRIPTION
**Pull request by EPashkin**
First part of #117

### CODE REVIEW

**Comment by gkoz** [comment]
Will `TypeKind::Enumeration` and the assumption that enums are passed directly become an issue when the converted enums appear? We already know `IconSize` will have to be a distinct enum on the Rust side and thus converted.

**Comment by EPashkin** [comment]
Then now only allow `TypeKind::Direct` ?
Or just make note, that we need divide `Library::Enumeration` to `TypeKind::Enumeration` and `TypeKind::Converted`?

**Comment by gkoz** [comment]
Maybe allowing overriding the type kind will suffice. Say, the `TypeKind::Enumeration` is still direct but we add a `TypeKind::ForceConversion` and apply that through config to `IconSize`, maybe `GType` too, etc.

`IconSize` is just ridiculous though because three(?) functions will take `Option<IconSize>` and I don't think handling this case in the code is worth the trouble.

**Comment by EPashkin** [comment]
Rebased

**Comment by gkoz** [comment]
@homu r+

**Comment by gkoz** [comment]
Okay, I had some doubts about this change but thought I just didn't understand it. Surely we'd want to comment out a function that has outparams we can't handle? `query_child_packing` still is wrong.

**Comment by EPashkin** [comment]
Yes, seems need comment function, if unsupported out params present.
Or there current way convert `&mut bool` to `*mut gboolean` ?
If not commenting function will be next stage.

On stage after it when we accept `TypeKind::Converted` function must look like this?
```
    fn query_child_packing<T: Upcast<Widget>>(&self, child: &T) -> (bool, bool, u32, PackType) {
        let mut expand = Default::default();
        let mut fill = Default::default();
        let mut padding = Default::default();
        let mut pack_type = Default::default();
        unsafe {
            ffi::gtk_box_query_child_packing(self.upcast().to_glib_none().0, child.upcast().to_glib_none().0, &mut expand, &mut fill, &mut padding, &mut pack_type);
        }
        (from_glib(expand), from_glib(fill), padding, pack_type)
    }
```

**Comment by gkoz** [comment]
Can't just convert a pointer, because the types have different sizes.
This code looks good.

**Pull request merged**
