### PR TITLE
Throwable functions

### LINKED ISSUE #130: Return Result for errors
For throwable function return value must return `Result` (see discussion beginning at https://github.com/gkoz/gir/issues/117#issuecomment-143070962).

2 types of throwable functions:
1) without other outs that will returns `Result<(), glib::Error>`
1.1) Examples of FFI function return guint:
gtk_builder_add_objects_from_string
1.2) Examples of FFI function return gboolean:
gtk_css_provider_load_from_path,
gtk_file_chooser_add_shortcut_folder,
gtk_file_chooser_set_current_folder_file,
gtk_page_setup_load_file,
gtk_print_settings_to_file
1.3) Examples of FFI functions return something usable
gtk_icon_info_load_icon,
gtk_recent_info_create_app_info,
gtk_recent_manager_lookup_item
2) with other outs that will returns tuple(or single value) instead () on good case
Examples:
gtk_builder_value_from_string,
gtk_icon_info_load_symbolic

~~Blocked by #103~~

### PR DESCRIPTION
**Pull request by EPashkin**
Closes #130

WIP

### CODE REVIEW

**Comment by EPashkin** [comment]
Working but needed some optimization on error detection

**Comment by EPashkin** [comment]
.. now it detects by comparing it name with "error"

**Comment by gkoz** [comment]
In most cases it's a [synthetical parameter](https://github.com/gkoz/gir/blob/master/src/parser.rs#L672-L683) though.

**Comment by EPashkin** [comment]
IMHO In all cases.

**Comment by gkoz** [comment]
In that case it seems straightforward to add a flag to `Parameter`.

**Comment by EPashkin** [comment]
You right, something like 'is_error: bool'

**Comment by EPashkin** [comment]
Other minor problem is double '(' in `Ok((ret))` but it accepted by compiler normally.
```
    pub fn new_from_file(file_name: &str) -> Result<PageSetup, glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let ret = from_glib_full(ffi::gtk_page_setup_new_from_file(file_name.to_glib_none().0, &mut error));
            if error.is_null() { Ok((ret)) } else { Err(from_glib_full(error)) }
        }
    }
```

**Comment by EPashkin** [comment]
Added flag in parameters

**Comment by gkoz** [comment]
Since `Error` is the universal error type, I'm inclined to reexport it in `gtk` making the return type more like `Result<PageSetup, Error>` (with appropriate `use Error;`).

**Comment by EPashkin** [comment]
IMHO better add `glib::Result<T>=Result<T, glib::Error>`

**Comment by EPashkin** [comment]
Not sure about need of reexporting `Error` or `Result`

**Comment by gkoz** [comment]
The `Result` alias make sense but I'm wary of cases where we might want to return `Result` from functions that don't throw. The error type there would be other than this `Error`, probably just `()`.

**Comment by EPashkin** [comment]
Is one reason why I prefer `glib::Result` in generated code.

**Comment by gkoz** [comment]
My considerations are these:
 * Popular types not particularly tied to `glib`, like `Error` and `Result<T> = Result<T, Error>` should be available in other libraries so the user wouldn't have to `extern crate glib` just to mention them.
 * When reexporting this `glib::Result` I'd hate to get into a situation where some module might need both `Result<T, Error>` and  `Result<T, ()>` (or perhaps `Result<T, SomeObscureError>`). The only non-`Error` `Result` so far is `gtk::init`. This might not turn out to be a practical problem.
 * If I'm not mistaken, adding the `Result<T, Error>` alias later won't be a breaking change because the type remains the same.

**Comment by EPashkin** [comment]
3. IMHO also

**Comment by gkoz** [comment]
For now let's change `glib::Error` to `Error` if it's not much trouble.

It's nice to see half of "unsupported outs" warnings gone.

**Comment by gkoz** [comment]
There's a slight problem with return (and outparam?) values conversions:
```rust
let ret = from_glib_full(ffi::gtk_page_setup_new_from_file(file_name.to_glib_none().0, &mut error));
if error.is_null() { Ok((ret)) } else { Err(from_glib_full(error)) }
```
We can't expect `ret` to be valid if there was an error. So this needs to be
```rust
let ret = ffi::gtk_page_setup_new_from_file(file_name.to_glib_none().0, &mut error);
if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
```

**Comment by EPashkin** [comment]
Fixed `Ok((ret))`.
Next be `Error` and then `Ok(from_glib_full(ret))`

**Comment by EPashkin** [comment]
Done `Error`

**Comment by EPashkin** [comment]
Done `Ok(from_glib_full(ret))`

**Comment by gkoz** [comment]
Perfect, thanks!
@homu r+

**Pull request merged**
