### PR TITLE
Hardcode some GType constants in gobject-sys

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by gkoz** [comment]
@homu r+

**Comment by EPashkin** [comment]
Not error, but no empty line in gobject-sys/src/lib:
```
#[allow(unused_imports)]
use glib_ffi::{gboolean, gconstpointer, gpointer, GType, Volatile};
pub const G_TYPE_INVALID: GType = 0 << G_TYPE_FUNDAMENTAL_SHIFT;
pub const G_TYPE_NONE: GType = 1 << G_TYPE_FUNDAMENTAL_SHIFT;
```

**Comment by gkoz** [comment]
D'oh. I'll add the newline. Thanks.

**Comment by gkoz** [comment]
Messed up the commit number :/ It's too hot here...

**Comment by EPashkin** [comment]
And remove newline for end also. Missed that on first look

**Comment by EPashkin** [comment]
If you can just replace last commit

**Comment by gkoz** [comment]
Alright I will replace the commit.

**Pull request merged**
