### PR TITLE
Cargo.toml generation and manipulation

### PR DESCRIPTION
**Pull request by gkoz**
Turns out the `toml-rs` library can't preserve the order of the items but at least it's deterministic.

### CODE REVIEW

**Comment by EPashkin** [comment]
Can you add `min_cfg_version = "3.4"` to `gir-gtk.toml` in this PR?
Not sure what value in other crates.

**Comment by gkoz** [comment]
I'll add some

**Comment by EPashkin** [comment]
Problems with gio: build.rs checks wrong package (at mininumum not builds on Windows).
```
const LIBRARY_NAME: &'static str = "gio";
const PACKAGE_NAME: &'static str = "gio-unix-2.0";
```

**Comment by gkoz** [comment]
Hmm, I must've botched the package name logic in a previous PR

**Comment by gkoz** [comment]
Yeah, it should've kept the first package it found, not the last one. Hang on

**Comment by EPashkin** [comment]
Thanks.

**Comment by gkoz** [comment]
@homu r+

**Pull request merged**
