### PR TITLE
Downcasts

### PR DESCRIPTION
**Pull request by EPashkin**
WIP

### CODE REVIEW

**Comment by EPashkin** [comment]
Now generated next code
```
fn get_content_area(&self) -> Option<Box> {
    unsafe {
        Widget::from_glib_none(ffi::gtk_dialog_get_content_area(self.upcast().to_glib_none().0)).downcast_unchecked()
    }
}
```
What correct conversion instead `downcast_unchecked()` for `Option<>`?
`downcast().ok()`?

**Comment by gkoz** [comment]
Hmm. I wrote this as
```rust
    fn get_content_area(&self) -> widgets::box_::Box {
        unsafe {
            Widget::from_glib_none(ffi::gtk_dialog_get_content_area(self.upcast().to_glib_none().0))
                .downcast_unchecked()
        }
    }
```
so apparently I didn't consider this nullable and `Option` isn't good there.

Generally in a nullable case I'd probably make it
```rust
            Widget::from_glib_none(ffi::gtk_dialog_get_content_area(self.upcast().to_glib_none().0))
                .map(|w| w.downcast_unchecked())
```

**Comment by EPashkin** [comment]
IMHO Result.Map still return result, not Option.

**Comment by gkoz** [comment]
Maybe `Downcast` should just be implemented for `Option`.

**Comment by gkoz** [comment]
Here's an actual working example:
```rust
    fn get_header_bar(&self) -> Option<HeaderBar> {
        unsafe {
            Option::<Widget>::from_glib_none(
                ffi::gtk_dialog_get_header_bar(self.upcast().to_glib_none().0))
                .map(Downcast::downcast_unchecked)
        }
    }
```

**Comment by EPashkin** [comment]
Made
```
fn get_content_area(&self) -> Option<Box> {
    unsafe {
        Option::<Widget>::from_glib_none(ffi::gtk_dialog_get_content_area(self.upcast().to_glib_none().0)).map(Downcast::downcast_unchecked)
    }
}
```
Found only ~30 `<return-value nullable="1" ` in gtk, none with nullable="0".
Seen some functions without nullable but NULL in doc (Ex. `gtk_dialog_get_widget_for_response`). 
So currently count all pointer result (calculated in `can_be_nullable_return`) except constructors as nullable.
If you find better solution, it can be changed later.

**Comment by gkoz** [comment]
The nullable issue seems to be impossible do handle without maintaining our own metadata. I've realized today that we don't have to enter all of the metadata by hand though, the generator could have an interactive mode and ask us about ambiguous functions then save the answers into the config.

**Comment by EPashkin** [comment]
Also we need solve possible conflict with std::boxed::Box, but it IMHO better done when we can compile gtk

**Comment by EPashkin** [comment]
Better no interactive mode in console generator.
And i don't like check all ambiguous functions in one time.

**Comment by EPashkin** [comment]
Also don't like rewrite toml, as it lost ordering and all comments

**Comment by gkoz** [comment]
Not in one time, more like `git add -p` that can be rerun many times and only saves any concrete answers you give.

The toml rewriting deficiency is unfortunate yes, someone was working on fixing that but it's not clear if we'll get that soon. That kind of metadata could live in a separate file though.

**Comment by EPashkin** [comment]
Agree that some `nullable_returns = ["gtk_dialog_get_widget_for_response"]` in config needed

**Comment by EPashkin** [comment]
IMHO implementation of interactive mode takes too much time and not give virtually no acceleration in comparison with the simple adding to configuration. As fast variant I can add prints or `warn!` for possible nullables.

**Comment by gkoz** [comment]
> Agree that some `nullable_returns = ["gtk_dialog_get_widget_for_response"]` in config needed

The default assumption should be a nullable return value (except from a constructor).

You're probably right about the interactive mode overhead.

**Comment by EPashkin** [comment]
> The default assumption should be a nullable return value (except from a constructor).

Its current mode (see `analysis\return_value`)

But you say that `gtk_dialog_get_content_area` not nullable in your opinion, for these exception we need some metadata, in config or not.
Not sure what cases is larger: not marked nullables, or not nullables in your mode.

**Comment by EPashkin** [comment]
IMHO nullable returns need better thinking and discussions, may be in Issue.
If current mode is good, and no mistakes in code, then PR ready to merge.

**Comment by gkoz** [comment]
Looks like `create_dir_all` is in the wrong place, should've been in `save_to_file`...

**Comment by EPashkin** [comment]
Agree, just waited for working directory check before "refactor" it.
Move it now?

**Comment by gkoz** [comment]
No, it's not urgent.

**Comment by gkoz** [comment]
Just one thing, could you `s/ctype/c_type/` for consistency?

**Comment by EPashkin** [comment]
Yes, it all different: `glib_name`, `c_type` :(

**Comment by gkoz** [comment]
There's less of `glib_name` now, we may be able to remove it. It's just `c_type` won't always be appropriate.

**Comment by EPashkin** [comment]
Renamed all including module

**Comment by gkoz** [comment]
Thanks!
@homu r+

**Comment by EPashkin** [comment]
This solves part of #102

**Pull request merged**
