### PR TITLE
Cfg condition

### PR DESCRIPTION
**Pull request by EPashkin**
Final part of #180

Example for config:
```
[[object]]
name = "Gtk.PaperSize"
status = "generate"
cfg_condition = "tst"
[[object.function]]
name = "is_ipp"
version = "3.16"
cfg_condition = "unix"
```

### CODE REVIEW

**Comment by EPashkin** [comment]
No cfg condition applied to sys mode

**Comment by EPashkin** [comment]
Something like this?

**Comment by EPashkin** [comment]
Rebased to master.

**Comment by gkoz** [comment]
More like just get rid of `cfg` and `cfg_1` moving the duplication down where it originates from
```
for cfg in &cfgs {
    contents.push(cfg.clone());
}
contents.push(format!("mod {};", module_name));
```
and so on

**Comment by EPashkin** [comment]
Then it IMHO become bad as we need push `cfgs` 3 times:
```
    contents.push(format!(""));
    for cfg in &cfgs {
        contents.push(cfg.clone());
    }
    contents.push(format!("mod {};", module_name));
    for cfg in &cfgs {
        contents.push(cfg.clone());
    }
    contents.push(format!("pub use self::{}::{};", module_name, analysis.name));
    if generate_trait(analysis) {
        for cfg in &cfgs {
            contents.push(cfg.clone());
        }
        contents.push(format!("pub use self::{}::{}Ext;", module_name, analysis.name));
        for cfg in &cfgs {
            traits.push(format!("\t{}", cfg));
        }
        traits.push(format!("\tpub use super::{}Ext;", analysis.name));
    }
```

**Comment by gkoz** [comment]
This has a chance of becoming nicer with `Vec::extend_from_slice` becoming available in 1.6:
```
contents.extend_from_slice(&cfgs);
```

**Comment by EPashkin** [comment]
Fixed and squashed.

**Comment by gkoz** [comment]
Thanks.
@homu r+

**Pull request merged**
