### PR TITLE
Generate upcasts

### PR DESCRIPTION
**Pull request by EPashkin**
Work in progress.
Again changes in library.

### CODE REVIEW

**Comment by EPashkin** [comment]
Rebasing

**Comment by EPashkin** [comment]
Fixed `get_name`.
Do not thinked that such a simple method works

**Comment by EPashkin** [comment]
Ready to merge

**Comment by gkoz** [comment]
Thanks.

**Comment by gkoz** [comment]
Could we make `Gir.toml` not default to generating the files outside of the current directory?
> `target_path = "../gtk"`

I know it saves backups but this still is potentially unpleasant.

**Comment by EPashkin** [comment]
You can just clone it in some subfolder. That won't do?
I'm prefer to see it's result compared with original in git.

**Comment by EPashkin** [comment]
It - `gir`, clone or move to subfolder, but you need create empty folders for gtk, as gir currently won't do it.

**Comment by gkoz** [comment]
If it was just 'target_path = output`, it would be possible to create a symlink that would point wherever your gtk dir is. The other way around is messy.

**Comment by EPashkin** [comment]
Ok. Then change 'target_path = "./gtk"' with adding it to `.gitignore'

**Comment by EPashkin** [comment]
Wait, i do it yourself, current version act strange on "./gtk" or "gtk".

**Pull request merged**
