### PR TITLE
Add out_parameters Mode::Combined for functions with nontrivial return types

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by EPashkin** [comment]
Seems it cover #144 with minor difference. Thanks.

**Comment by gkoz** [comment]
I wasn't completely sure if `ret` should be the first or last. It probably makes more sense to put it first like suggested in that issue.

**Comment by gkoz** [comment]
And the return value is in the first position now.

**Comment by EPashkin** [comment]
Thanks.

**Comment by gkoz** [comment]
@homu r+

**Pull request merged**
