### PR TITLE
Comment out functions with ignored records and classes among parameters

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by EPashkin** [comment]
Only find strange changes in `gtk_search_bar_connect_entry` it now commented without any visible 'Ignored' for `Entry`.
Not sure that needed fix.

**Comment by EPashkin** [comment]
```
    //#[cfg(gtk_3_10)]
    //pub fn connect_entry<T: Upcast<Entry>>(&self, entry: &T) {
    //    unsafe { TODO: call ffi::gtk_search_bar_connect_entry() }
    //}
```

**Comment by gkoz** [comment]
Looks like `Entry` is not in the toml and so ignored by default. Adding it restores this method.

**Comment by EPashkin** [comment]
Yes, but error that /*Ignored*/ not shown before `Entry` as printed by other methods.
IMHO it minor and can be ignored.

**Comment by gkoz** [comment]
I'll see if it can be fixed easily

**Comment by EPashkin** [comment]
Good fix.

**Comment by gkoz** [comment]
@homu r+

**Pull request merged**
