### PR TITLE
Rewrite files with CRLF line terminators

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by gkoz** [comment]
Hmm, putting in CRLFs? I thought git should be taking care of that with something like
```
git config --global core.autocrlf true
```

**Comment by gkoz** [comment]
Or I'm reading the diff backwards and you're removing them :)

**Comment by gkoz** [comment]
@homu r+

**Comment by EPashkin** [comment]
core.autocrlf=true marks toml.lock always changed, as it restored with CRLF, but recreated by cargo with CR.
Also some version `sh` that (Cygwin) that don't undershand script with CRLF, so I have autoclf=false by default.
Now I try change IDE to emacs, so sometimes make mistake with creating new file.

**Comment by gkoz** [comment]
Will putting this `.gitattributes` help?
```
Cargo.lock eol-lf
```

If that helps I'd consider teaching `cargo new` to add that line. You could also put that in your global `gitattributes` file.

**Comment by EPashkin** [comment]
`.gitattributes` with
```
Cargo.lock eol=lf
*.sh eol=lf
```
seems solves problem.
Global file also works fine.

**Pull request merged**
