### PR TITLE
Stop stripping prefixes from enums and bitfields

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by EPashkin** [comment]
Not sure that we really need do that.
If you do it because xlib::xevent, then it xlib-2.0.gir problem. It has line
`<union name="XEvent" c:type="XEvent"/>`

**Comment by gkoz** [comment]
More because it's inconsistent to strip some identifiers but not others, I added stripping imitating the manual crates but that's silly. The front end crates will have to reexport any symbols they want under different names.

**Comment by EPashkin** [comment]
Then ok.

**Comment by gkoz** [comment]
@homu r+

**Pull request merged**
