### PR TITLE
Generate record functions

### PR DESCRIPTION
**Pull request by EPashkin**
WIP

### CODE REVIEW

**Comment by gkoz** [comment]
I'll work on supporting `volatile`.

**Comment by EPashkin** [comment]
Almost done it

**Comment by gkoz** [comment]
I'll do something else then :)

**Comment by EPashkin** [comment]
Can you check time::Tm?

**Comment by gkoz** [comment]
That's a different struct. It's not clear if anyone has defined the C `struct tm`. IMO we'll be fine without it.

**Comment by EPashkin** [comment]
it defined with  `repl[C]`

**Comment by gkoz** [comment]
```C
struct tm
{
  int tm_sec;			/* Seconds.	[0-60] (1 leap second) */
  int tm_min;			/* Minutes.	[0-59] */
  int tm_hour;			/* Hours.	[0-23] */
  int tm_mday;			/* Day.		[1-31] */
  int tm_mon;			/* Month.	[0-11] */
  int tm_year;			/* Year	- 1900.  */
  int tm_wday;			/* Day of week.	[0-6] */
  int tm_yday;			/* Days in year.[0-365]	*/
  int tm_isdst;			/* DST.		[-1/0/1]*/
  long int tm_gmtoff;		/* Seconds east of UTC.  */
  const char *tm_zone;		/* Timezone abbreviation.  */
};
```
vs
```rust
pub struct Tm {
    pub tm_sec: i32,
    pub tm_min: i32,
    pub tm_hour: i32,
    pub tm_mday: i32,
    pub tm_mon: i32,
    pub tm_year: i32,
    pub tm_wday: i32,
    pub tm_yday: i32,
    pub tm_isdst: i32,
    pub tm_utcoff: i32,
    pub tm_nsec: i32,
}
```

**Comment by EPashkin** [comment]
Bad

**Comment by gkoz** [comment]
Removing `volatile` is not quite what I had in mind. It's better to create a `pub type Volatile<T>(T)` wrapper.

**Comment by EPashkin** [comment]
Ok, then you can do it ;)

**Comment by EPashkin** [comment]
About `GObjectClass`: Seems `ffi_inner` on `Fundamenta::Pointer` also need reworking by you.
I'm done with this PR.

**Comment by EPashkin** [comment]
Or as temporary solution i can add it hardcoded

**Comment by gkoz** [comment]
I didn't expect `ffi_type` to ignore "c:type mismatch" in case of `<type name="ContainerClass" c:type="GObjectClass*"/>`...

**Comment by EPashkin** [comment]
I can't find way to hardcode it :(

**Comment by EPashkin** [comment]
And I don't ended refactoring of read_function, continue in other PR tomorrow.
Stuck in multiple borrow of self in `read_global_function` when change it using `read_function_and_then`

**Comment by gkoz** [comment]
The `ffi_type` functions have grown monstrous. I'll have to write some tests and refactor after this PR.

**Comment by EPashkin** [comment]
Now all builds. Thank.

**Comment by EPashkin** [comment]
Any unfinished work for sys?

**Comment by gkoz** [comment]
Constants (with blacklisting support) and a simple build script (like in `gdk-sys`). We'll probably have to look into features/versions soon but it's not urgent.

**Comment by EPashkin** [comment]
Build script check one library from
`<package name="gtk+-3.0"/>`?
Can those names stored in namespaces? If I not wrong one package <=> one namespace.

**Comment by EPashkin** [comment]
Seems can be 2 or 0 package in one namespace `Gio-2.0.gir`.
IMHO we can't auto separate unix specific package, that make generating build script impossible.

**Comment by gkoz** [comment]
Yes we can put this info into `Namespace`. And if there's more than one package (seems specific to `Gio`) we can take the first one. And then blacklist platform-specific `Gio` stuff.

**Comment by EPashkin** [comment]
Seems github not good with continued PR, still shows your commits and comment for PR83.
Rebased just in case.

**Comment by gkoz** [comment]
Thanks.
@homu r+

**Pull request merged**
