### PR TITLE
Tests gobject

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by gkoz** [comment]
Thanks!
Let's see if I've fixed `ffi_type` sufficiently.
@homu r+

**Comment by EPashkin** [comment]
Only last va_list problem and warning

**Comment by gkoz** [comment]
This'll be easier to fix after merging.

**Comment by gkoz** [comment]
Uh-oh. We simply can't support `va_list` so it's blacklisting time.

**Comment by EPashkin** [comment]
IMHO good way to blacklisting add
```
[[objects]
name = "GObject.SignalCVaMarshaller"
status = "ignore"
```
and check status in `generate_aliases`.
PS. Commenting `pub type GSignalCVaMarshaller = GVaClosureMarshal;` fixed build

**Comment by EPashkin** [comment]
Also we can check all non-internal namespaces in `fix_external_name`

**Comment by gkoz** [comment]
This doesn't seem appropriate under `[[objects]]`. Also for the purpose of sys modules I'd like something less verbose, like a single array with blacklisted identifiers, e.g.
```toml
ignore = [
    "SignalCVaMarshaller",
    "SomethingElse",
]
```

**Comment by gkoz** [comment]
Yeah, bad types from external namespaces could be a problem...

**Comment by EPashkin** [comment]
We can just rename [[objects]] to something else [[identifiers]]

**Comment by EPashkin** [comment]
This way we don't need add second check.

**Comment by gkoz** [comment]
toml allows this BTW
```toml
[[GObject.SignalCVaMarshaller]]
status = "ignore"
```
Could save some typing.

**Comment by EPashkin** [comment]
But how to detect that it is `objects` ?

**Comment by gkoz** [comment]
If the generator went through the objects (and other items) it finds in the library, it would know and just check them against the config.

**Comment by EPashkin** [comment]
So we need store toml in environment?

**Comment by EPashkin** [comment]
And do parsing on every request?

**Comment by gkoz** [comment]
I assumed it's parsed once and held in memory :)

**Comment by EPashkin** [comment]
Yes, it parsed as toml file, but we needed parse "status=ignore" on every request, as we can't "combine" all old [[objects]] to one category and parse to own format.

**Comment by gkoz** [comment]
Asking the `toml::Table` if it has a key `status` inside a table `Widget` inside a table `Gtk` should not involve parsing. (I should've put single brackets in that example: `[Gtk.Widget]`)

**Comment by EPashkin** [comment]
But we needed parse `status`

**Comment by gkoz** [comment]
I see. Okay, currently all items are uniform pairs of name and status so we actually can parse them once. If some items' configs get distinct keys in the future, we surely can manage that somehow (the library knows which is which after all).

**Comment by gkoz** [comment]
But explicitness could be a virtue too I guess.

**Comment by EPashkin** [comment]
We can count `ignore` as simply alias for [[objects]]name=...\status='ignore'

**Comment by EPashkin** [comment]
The main thing from my point of view, that is stored in name => Status. With the test of the dubbing, etc.

**Comment by gkoz** [comment]
An `ignore` shorthand is okay.

**Pull request merged**
