### PR TITLE
rust_type: only consider Option for Pointer, Object and Interface types

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by EPashkin** [comment]
As I see it only affect gesture_drag.rs whose 2 function has `f64` out parameters with `bool` return and must be fixed in #119, so I not sure about this way.

**Comment by EPashkin** [comment]
If you will do any changes in this PR, swap commits please

**Comment by gkoz** [comment]
> As I see it only affect gesture_drag.rs whose 2 function has f64 out parameters with bool return and must be fixed in #119, so I not sure about this way.

Yes and no. The previous change aiming to avoid `Option` for containers wasn't entirely correct. It's less error prone to just say: only pointers have a notion of nullability.

Updated.

**Comment by EPashkin** [comment]
By way, as we don't plan pass NULL to out parameters, may be also change parser to set all outs nonnullable?

**Comment by EPashkin** [comment]
> Yes and no. The previous change aiming to avoid Option for containers wasn't entirely correct. It's less error prone to just say: only pointers have a notion of nullability.

Understand. No problem then.

**Comment by gkoz** [comment]
> By way, as we don't plan pass NULL to out parameters, may be also change parser to set all outs nonnullable?

Correction: `nullable` describes the returned value, it's `optional` that allows passing a `NULL` pointer in. I don't see the benefit of doing this.

**Comment by EPashkin** [comment]
For `gtk_gesture_drag_get_offset` both out parameters marked as `nullable` in GIR

**Comment by gkoz** [comment]
That might be a mistake. See https://wiki.gnome.org/action/show/Projects/GObjectIntrospection/Annotations#Type_signature

**Comment by EPashkin** [comment]
> Indicates that NULL may be a valid value for a parameter (in, out, inout)

Don't it mean that if you don't wan't `x` then can pass NULL pointer as value?

**Comment by gkoz** [comment]
Together with 
>  (optional) For (out) parameters, NULL signifies that the output value is to be ignored.

I consider "value" to be the actual data returned in the outparameter and `nullable` being strictly orthogonal to `optional`. The majority of the annotations are consistent with this interpretation.

**Comment by EPashkin** [comment]
`//parameter[@direction="out" and @nullable]` shows 13 parameters
`//parameter[@direction="out" and @optional]` shows many parameters,
may be you right and it just mistake (as gdouble can't be NULL).

**Comment by gkoz** [comment]
It's valid for a value to be `nullable` independently from being `optional` and I have the impression that many items that should be tagged `nullable` are not, just as the usual return values.

**Comment by gkoz** [comment]
@homu r+

**Pull request merged**
