### PR TITLE
Change default output directory

### PR DESCRIPTION
**Pull request by EPashkin**
Found strange bug, sometimes it analyzing 1-2 files (always including RadioButton).

### CODE REVIEW

**Comment by gkoz** [comment]
> sometimes it analyzing 1-2 files (always including RadioButton)

Fixed in 97726b9.

**Comment by EPashkin** [comment]
Yes, tnx, seems fixed. But why in skipps items that before `Ignored`?

**Comment by gkoz** [comment]
The order of the toml items is not preserved, there's a `HashMap` somewhere I guess. This surprised me too.

**Comment by EPashkin** [comment]
Yes, it random-based hashed, and I used it in GObjects :(
Started change to Vec, as i may need sort order by added https://github.com/EPashkin/gir/tree/change_GObjects_to_Vec.
But now i think is ok.

PS. Can I comment `show(&library);` in next PR?

**Comment by gkoz** [comment]
> Can I comment show(&library); in next PR?

Yes, it's pretty useless.

**Pull request merged**
