### PR TITLE
Don't make backups

### PR DESCRIPTION
**Pull request by EPashkin**
Can make instead conditional compilation or config options

### CODE REVIEW

**Comment by gkoz** [comment]
We could add a command-line option but with git everywhere the backups just seem redundant and slightly annoying.

**Comment by EPashkin** [comment]
Ok, I make command line options -b, --make_backup

**Comment by EPashkin** [comment]
Done

**Comment by EPashkin** [comment]
What better do with classes functions?
Ex. `gtk_window_get_default_icon_name`?

**Comment by gkoz** [comment]
> What better do with classes functions?
Ex. gtk_window_get_default_icon_name?

Static methods probably. If I understand the question right.

**Comment by gkoz** [comment]
@homu r+

**Comment by EPashkin** [comment]
> Static methods probably. If I understand the question right.

```
impl Window {
    pub fn get_default_icon_name() -> String {
        unsafe { from_glib_none(ffi::gtk_window_get_default_icon_name()) }
    }
}
```
Ok.

**Comment by gkoz** [comment]
Looks good.

**Pull request merged**
