### PR TITLE
Generate sys interface functions

### PR DESCRIPTION
**Pull request by EPashkin**
WIP, don't merge.
Just to inform about.

### CODE REVIEW

**Comment by gkoz** [comment]
I'm deep into breaking the parser to allow anonymous unions and functions. Hopefully there won't be many conflicts :) I'm making these `Function` fields optional but most of the time unwrapping them should be safe:
```rust
    pub name: Option<String>,
    pub c_identifier: Option<String>,
```

**Comment by gkoz** [comment]
Actually, the `name` might not become optional, I could've gotten carried away.

**Comment by EPashkin** [comment]
Ok, i try don't touch library.
Can you rename `c_identifier` to `glib_type_name`?

**Comment by EPashkin** [comment]
Ignore last.

**Comment by EPashkin** [comment]
Ready to merge
I thought to do:
1) merge generate_classes_xxx, but only for 2 cases too many work
2) use library::*, but don't like mix with this PR

**Comment by EPashkin** [comment]
3) Add trait to library GlibName { fn glib_name(&self) -> &str; } (this also allow merge `generate_classes_structs`), but it better be in library

**Comment by gkoz** [comment]
>  merge generate_classes_xxx, but only for 2 cases too many work

Not sure which ones these are, if it's `generate_classes_structs` and `generate_interfaces_structs`, they seem too small to bother.

The trait might be useful.. if every implementing type is able to return a slice.

**Comment by gkoz** [comment]
Ah, I think I see know. `generate_interface_funcs` is it? Can't the function take a `&[Function]` instead of the `Interface` or `Class`?

**Comment by EPashkin** [comment]
Ok, it simpler, that add traits or macros, I do that.

**Comment by EPashkin** [comment]
Done

**Comment by EPashkin** [comment]
Still leave class name for better search

**Comment by gkoz** [comment]
Thanks!

**Pull request merged**
